### ISSUE TITLE
Migrate this repo into Orion Monorepo

### ISSUE THREAD

**Issue by adrianmc** [chunsli/simple-todos#11]
@hyperh See if you can set a milestone to merge in your testing branch. Subsequent to that, we should move this into the Orion repo under its own directory—maybe `orion-meteor-package-dev`. The `dev` distinction is because this project includes a Meteor app used for testing as well as the package itself.

In the future, we may want a folder in the monorepo with only the package contents inside (like other open-source packages on GH).

**Comment by hyperh** [comment]
Or can do a symbolic link to the package file from the Meteor app.

Proposing the following structure:
```
orion-frontend
example
  meteor
meteor-package
```

**Comment by adrianmc** [comment]
@hyperh good idea, although I'd change up the naming a bit:

```
orion-frontend
orion-node-server
orion-meteor-example
orion-meteor-package
```
