### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by adrianmc** [chunsli/simple-todos#9]
From #8 

I feel conflicted about it because it's only been 3 months since 1.3 dropped (on Mar 28). Can you use other ES6 features on 1.2 packages? Or is it only Import/Export (modules) that doesn't work?

**Comment by hyperh** [comment]
I just tested using `const` in my package without depending on 1.3. Works. But I'm guessing it works b/c the app itself is 1.3+ already. I'll see what happens in a pre-1.3 app, probably won't though.

**Comment by adrianmc** [comment]
I think you have to require the `ecmascript` package for 1.2 Meteor apps. 

> Beginning today, ECMAScript 2015 is now the official JavaScript of the Meteor platform.  Every new Meteor project now uses ES2015 by default, in every JS file.  Want to use ES2015 in an existing app?  Just add the new ecmascript package.  We've taken great care to make our ES2015 support 100% backwards compatible: your existing code will continue to work unchanged, and you can make the transition incrementally mixing and matching new ES2015 and traditional JavaScript, even in the same files and functions.

Source: http://info.meteor.com/blog/announcing-meteor-1.2

**Comment by hyperh** [comment]
Ok so if we support 1.2+ is that ok?

**Comment by adrianmc** [comment]
1.2 dropped on Sep 22, 2015, so yeah I think that's pretty darn good.

**Comment by hyperh** [comment]
Cool, I'll revise to use ES6 then. Writing ES5 was so disorganized.

**Comment by hyperh** [comment]
Resolved by https://github.com/chunsli/simple-todos/issues/9

**Comment by adrianmc** [comment]
how come this was reopened?

**Comment by hyperh** [comment]
Cuz the pull request wasn't accepted yet.
